language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g eslint
install: npm install
script:
  - npm run test
sudo: false
dist: trusty
env:
  global:
    - COMMIT_AUTHOR_EMAIL: 'antoine.van-serveyt@hotmail.be'
