language: node_js
node_js:
  - '8'
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_2537babbf80b_key -iv $encrypted_2537babbf80b_iv -in deploy\\deploy_key.enc -out deploy\\deploy_key.pem -d
  - npm install -g eslint
install: npm install
script:
  - bash ./deploy/deploy.sh
dist: trusty
env:
  global:
    - ENCRYPTION_LABEL: '2537babbf80b'
    - COMMIT_AUTHOR_EMAIL: 'antoine.van-serveyt@hotmail.be'
